/**
 * Benchmark data contract — the plain-data shapes the SHARED scenario
 * generators (`tests/bench/lib/scenarios/forms.ts`) are expressed in, plus the
 * deterministic operation-sequence types the runners send to the in-page
 * harness (`tests/bench/lib/harness-protocol.ts`) through the browser driver
 * (`tests/bench/utils/agent-browser.ts`). Both benchmarked implementations
 * consume the exact same data, so scenarios stay implementation-neutral.
 *
 * Rules enforced by design:
 * - The driver and the harness operations must not know about scenarios.
 * - Scenarios must not know about implementations.
 * - Every timed operation is sampled in-page with `performance.now()` by the
 *   fixture harness, so both implementations measure identically.
 */

export type BenchImplementation = 'current' | 'main';

export interface BenchFieldOption {
  readonly value: string;
  readonly label: string;
}

export interface BenchArrayObjectConfig {
  readonly layout?: 'stack' | 'grid';
  readonly columns?: number;
  readonly fields: readonly BenchField[];
}

export interface BenchArrayConfig {
  readonly itemType?: string;
  readonly minItems?: number;
  readonly maxItems?: number;
  readonly defaultValue?: unknown;
  readonly objectConfig?: BenchArrayObjectConfig;
}

export interface BenchField {
  readonly name: string;
  readonly type: string;
  readonly label?: string;
  readonly placeholder?: string;
  readonly required?: boolean;
  readonly options?: readonly BenchFieldOption[];
  readonly page?: number;
  readonly tab?: string;
  readonly arrayConfig?: BenchArrayConfig;
}

export interface BenchPageConfig {
  readonly page: number;
  readonly title: string;
  readonly description?: string;
}

export interface BenchTabConfig {
  readonly id: string;
  readonly label: string;
}

/** One array-field operation inside a deterministic scenario op sequence. */
export type BenchArrayOp = { readonly op: 'add' } | { readonly op: 'remove'; readonly itemIndex: number };

/**
 * One memory-scenario interaction. Sequences are generated by the shared
 * scenario generators and executed unchanged by both fixtures.
 */
export type BenchMemoryOp =
  | { readonly op: 'type'; readonly fieldName: string; readonly text: string }
  | { readonly op: 'switchPage'; readonly pageNumber: number }
  | { readonly op: 'arrayAdd'; readonly fieldName: string }
  | { readonly op: 'arrayRemove'; readonly fieldName: string; readonly itemIndex: number };

/**
 * One synthetic streaming chunk for the current-only `stream-100chunks`
 * scenario: the plain-data twin of the AI scheduler's `text-delta` event. The
 * fixture converts these to real `AiStreamEvent`s and feeds them through the
 * real `AiStreamScheduler`; `receivedAt` simulates the chunk's arrival tick.
 */
export interface BenchStreamChunkEvent {
  readonly type: 'text-delta';
  readonly delta: string;
  readonly receivedAt: number;
}
