import type { BenchArrayOp, BenchMemoryOp } from './adapter-types';

/**
 * JSON-serializable protocol between the bench driver
 * (`tests/bench/utils/agent-browser.ts`) and the in-page harness global the
 * committed fixtures expose (`window.__benchHarness`, built by
 * `tests/bench/fixtures/current-consumer/main.tsx` and
 * `tests/bench/fixtures/main-consumer/main.tsx`).
 *
 * Every harness method takes plain-serializable arguments and returns a plain
 * result object whose numbers are milliseconds sampled in-page with
 * `performance.now()` (DECISION-2 revised). The driver summarizes those samples
 * with the shared `bench-timing.ts` statistics — identical warmup/median/p75/
 * min/max math, applied to browser-collected samples.
 *
 * Deterministic operation sequences (page switches, tab switches, array
 * operations, the memory workload) are generated by the shared scenario
 * generators and handed to the sequence loops below, so both implementations
 * execute byte-identical op lists.
 *
 * This module is TYPE-ONLY by design: the fixture bundles and the node driver
 * both import it, so the protocol has exactly one definition while the programs
 * stay independent.
 */

/** Answers "is the scenario form mounted and the harness callable?". */
export interface HarnessStatus {
  readonly ready: boolean;
  /** The `?scenario=` value the page was opened with. */
  readonly scenario: string;
  /** Populated when the scenario id is unknown or mounting failed. */
  readonly error?: string;
}

/** Loop options shared by every harness timing loop. */
export interface HarnessLoopOptions {
  /** Untimed runs executed before sampling begins. */
  readonly warmupRuns: number;
  /** Timed runs whose samples are returned. */
  readonly measuredRuns: number;
}

/** Result of the mount loop (initial render + commit of the scenario form). */
export interface HarnessMountResult {
  readonly samples: readonly number[];
  /** Distinct named controls inside the freshly mounted form (last run). */
  readonly renderedFieldCount: number;
}

/** Result of the keystroke loop (one input event per character). */
export interface HarnessKeystrokeResult {
  readonly samples: readonly number[];
  /** Input events dispatched per run (the typing workload length). */
  readonly eventCount: number;
  /** The typed control's DOM value after the final run. */
  readonly finalInputValue: string;
  /** The form-state value for the typed field after the final run. */
  readonly formValue: unknown;
}

/** Result of the submit loop (zod validation + `onSubmit` round trip). */
export interface HarnessSubmitResult {
  readonly samples: readonly number[];
  /** How many submits actually reached the consumer `onSubmit`. */
  readonly submitCount: number;
  /** Warmup + measured submits the loop attempted. */
  readonly expectedSubmitCount: number;
}

/**
 * Result of a page-switch or tab-switch sequence loop. `samples` carries one
 * sample per executed switch across every measured run (warmup sequence runs
 * are untimed), so a sequence of N switches over R measured runs yields N*R
 * samples.
 */
export interface HarnessSwitchResult {
  readonly samples: readonly number[];
  /** 1-based current page after the final run (page loops) or 0-based active tab index. */
  readonly activeIndex: number;
}

/** Result of an array add/remove sequence loop (one sample per operation). */
export interface HarnessArrayOpResult {
  readonly samples: readonly number[];
  /** Rendered array items after the final operation. */
  readonly itemCount: number;
}

/** One in-page heap reading (megabytes) taken at a workload checkpoint. */
export interface HarnessMemoryCheckpoint {
  /** Interactions executed before this reading (0 = workload baseline). */
  readonly interactions: number;
  readonly heapMb: number;
}

/**
 * The driver-assembled result of the memory workload: which heap API the page
 * used and one checkpoint per interval plus the pre-workload baseline. The
 * driver merges the per-chunk op executions and the between-chunk heap
 * snapshots into this shape (each piece is a separate `agent-browser eval` —
 * a single `measureUserAgentSpecificMemory()` call can take 10s+, so ops and
 * heap reads must never share an eval). Growth and slope are computed by the
 * shared runner glue (`run-common.ts`) so both implementations apply identical
 * math.
 */
export interface HarnessMemoryResult {
  /** Which Chromium heap API produced `heapMb` (recorded as an artifact note). */
  readonly apiName: string;
  /** Interactions executed (the workload length). */
  readonly opCount: number;
  readonly checkpoints: readonly HarnessMemoryCheckpoint[];
}

/** One heap reading as the page reports it (see `BenchHarnessGlobal.heapSnapshot`). */
export interface HarnessHeapSnapshot {
  readonly apiName: string;
  readonly heapMb: number;
}

/** Result of the in-page memory op execution (ops only — heap reads are separate). */
export interface HarnessMemoryRunResult {
  readonly opCount: number;
}

/**
 * Result of ONE in-page streaming run (`stream-100chunks`, current-only): the
 * 100 synthetic chunks are fed through the REAL `AiStreamScheduler` into the
 * minimal transcript, one chunk per scheduler frame tick, and every flush's
 * React commit is awaited before the next chunk is enqueued.
 */
export interface HarnessStreamRunResult {
  /** Per-run totals: the summed scheduler-flush → React-commit latency of all chunks. */
  readonly flushMsTotal: number;
  /** React commits of the transcript tree during the run (commit-counting hook). */
  readonly commitCount: number;
  /** Scheduler flush invocations during the run (the scheduler's onFlush calls). */
  readonly flushCount: number;
  /** Chunks fed through the scheduler (verification against the workload). */
  readonly chunkCount: number;
  /** Transcript text after the run (must equal the accumulated payload). */
  readonly finalText: string;
}

/**
 * The current-only streaming harness surface (`stream-100chunks`). Kept
 * SEPARATE from `BenchHarnessGlobal` because the main-baseline fixture has no
 * streaming scenario — the current fixture exposes
 * `BenchHarnessGlobal & HarnessStreamLoop`.
 */
export interface HarnessStreamLoop {
  streamLoop(options: HarnessLoopOptions): Promise<HarnessStreamRunResult>;
}

/**
 * The driver-assembled stream result: per-run flush totals and commit counts
 * (one pair per measured run — the loop executes ONE measured run per eval so
 * no eval approaches the CLI's CDP action timeout) plus the final run's
 * verified state. Warmup runs are executed in a single untimed eval and
 * contribute no samples. Per-run `flushCount`/`commitCount` equalities are
 * asserted in-page before a run is allowed to return.
 */
export interface HarnessStreamResult extends Omit<HarnessStreamRunResult, 'flushMsTotal' | 'commitCount' | 'flushCount'> {
  readonly flushMsTotals: readonly number[];
  readonly commitCounts: readonly number[];
}

/** The in-page harness surface (all methods JSON-serializable in and out). */
export interface BenchHarnessGlobal {
  status(): HarnessStatus;
  mountLoop(options: HarnessLoopOptions): Promise<HarnessMountResult>;
  keystrokeLoop(fieldName: string, text: string, options: HarnessLoopOptions): Promise<HarnessKeystrokeResult>;
  submitLoop(options: HarnessLoopOptions): Promise<HarnessSubmitResult>;
  switchPageSequenceLoop(pageNumbers: readonly number[], options: HarnessLoopOptions): Promise<HarnessSwitchResult>;
  switchTabSequenceLoop(tabIndices: readonly number[], options: HarnessLoopOptions): Promise<HarnessSwitchResult>;
  arraySequenceLoop(
    fieldName: string,
    ops: readonly BenchArrayOp[],
    options: HarnessLoopOptions,
  ): Promise<HarnessArrayOpResult>;
  /** Executes the workload ops in order (no heap reads inside). */
  memoryLoop(ops: readonly BenchMemoryOp[]): Promise<HarnessMemoryRunResult>;
  /**
   * One heap reading, settled over two frames first. Throws when no Chromium
   * heap API is available, so the scenario fails loudly instead of skipping.
   */
  heapSnapshot(): Promise<HarnessHeapSnapshot>;
}
