import type { CompatibilityExample } from './example-manifest';

const surveySource =
  'old_version_for_knowledge_purpose/apps/web/src/app/docs/examples/survey-form.tsx';
const conditionalPagesSource =
  'old_version_for_knowledge_purpose/apps/web/src/app/docs/examples/conditional-pages-form.tsx';
const persistenceSource =
  'old_version_for_knowledge_purpose/apps/web/src/app/docs/examples/persistence-form.tsx';
const tabbedSource =
  'old_version_for_knowledge_purpose/apps/web/src/app/docs/examples/tabbed-form.tsx';
const rentalCarFlowSource =
  'old_version_for_knowledge_purpose/apps/web/src/app/docs/examples/rental-car-flow-form.tsx';
const analyticsTrackingSource =
  'old_version_for_knowledge_purpose/apps/web/src/app/docs/examples/analytics-tracking-form.tsx';

export const surveyCompatibilityExample = {
  id: 'survey-form-dynamic-options',
  group: 'behavior',
  sourceFile: surveySource,
  publicBehavior: [
    'compatibility examples preserve conditional survey fields based on satisfaction, recommendation, referral source, and country.',
    'State/province options are dynamic and depend on the selected country.',
    'Feature selection is capped at three selected values.',
  ],
  schemaFields: {
    satisfaction: ['number', 'required'],
    recommend: ['enum', 'required'],
    improvements: ['string', 'optional'],
    referralSource: ['string', 'optional'],
    otherSource: ['string', 'optional'],
    features: ['array'],
    country: ['string', 'optional'],
    state: ['string', 'optional'],
  },
  fields: [
    { name: 'satisfaction', type: 'rating', config: ['max:5', 'showValue'] },
    { name: 'recommend', type: 'radio', options: ['yes', 'maybe', 'no'] },
    { name: 'improvements', type: 'textarea', conditional: 'satisfaction is less than 4' },
    { name: 'referralSource', type: 'select', conditional: 'recommend is yes', options: ['friend', 'social', 'search', 'ad', 'other'] },
    { name: 'otherSource', type: 'text', conditional: 'referralSource is other' },
    { name: 'features', type: 'multiSelect', options: ['forms', 'validation', 'analytics', 'integrations', 'api'], config: ['maxSelections:3'] },
    { name: 'country', type: 'select', options: ['us', 'ca', 'uk', 'au'] },
    {
      name: 'state',
      type: 'select',
      conditional: 'country has a value',
      options: ['dynamic:country'],
      optionSets: {
        us: ['ca', 'ny', 'tx', 'fl'],
        ca: ['on', 'qc', 'bc', 'ab'],
        uk: ['england', 'scotland', 'wales', 'ni'],
        au: ['nsw', 'vic', 'qld', 'wa'],
      },
    },
  ],
  optionsUsed: ['field.conditional', 'dynamic field options', 'ratingConfig', 'multiSelectConfig'],
  returnHelpersUsed: ['Form'],
  assertionsRequired: [
    'improvements is visible when satisfaction is 1, 2, or 3 and hidden when satisfaction is 4 or 5',
    'referralSource is visible only when recommend is yes',
    'otherSource is visible only when referralSource is other',
    'state options for us, ca, uk, and au are selected by country value rather than array position',
  ],
} satisfies CompatibilityExample;

export const conditionalPagesCompatibilityExample = {
  id: 'conditional-pages-form',
  group: 'behavior',
  sourceFile: conditionalPagesSource,
  publicBehavior: [
    'compatibility examples preserve conditional page visibility for individual and business application paths.',
    'Premium options page appears only when needsPremium is true.',
    'Contact information page remains visible for every application path.',
  ],
  schemaFields: {
    applicationType: ['enum', 'required'],
    firstName: ['string', 'optional'],
    lastName: ['string', 'optional'],
    dateOfBirth: ['date', 'optional'],
    personalId: ['string', 'optional'],
    companyName: ['string', 'optional'],
    businessType: ['enum', 'optional'],
    taxId: ['string', 'optional'],
    employeeCount: ['number', 'optional'],
    needsPremium: ['boolean'],
    premiumFeatures: ['array', 'optional'],
    premiumBudget: ['enum', 'optional'],
    email: ['string', 'email', 'required'],
    phone: ['string', 'required'],
    preferredContact: ['enum', 'required'],
  },
  fields: [
    { name: 'applicationType', type: 'radio', page: 1, options: ['individual', 'business'] },
    { name: 'firstName', type: 'text', page: 2, conditional: 'applicationType is individual' },
    { name: 'lastName', type: 'text', page: 2, conditional: 'applicationType is individual' },
    { name: 'dateOfBirth', type: 'date', page: 2, conditional: 'applicationType is individual' },
    { name: 'personalId', type: 'text', page: 2, conditional: 'applicationType is individual' },
    { name: 'companyName', type: 'text', page: 3, conditional: 'applicationType is business' },
    { name: 'businessType', type: 'select', page: 3, conditional: 'applicationType is business', options: ['llc', 'corporation', 'partnership', 'sole_proprietorship'] },
    { name: 'taxId', type: 'text', page: 3, conditional: 'applicationType is business' },
    { name: 'employeeCount', type: 'number', page: 3, conditional: 'applicationType is business', config: ['min:1'] },
    { name: 'needsPremium', type: 'checkbox', page: 4 },
    { name: 'premiumFeatures', type: 'multiSelect', page: 5, conditional: 'needsPremium is true', options: ['analytics', 'support', 'integrations', 'whitelabel', 'sla'], config: ['searchable', 'maxSelections:5'] },
    { name: 'premiumBudget', type: 'radio', page: 5, conditional: 'needsPremium is true', options: ['basic', 'standard', 'premium'] },
    { name: 'email', type: 'email', page: 6 },
    { name: 'phone', type: 'phone', page: 6 },
    { name: 'preferredContact', type: 'radio', page: 6, options: ['email', 'phone', 'both'] },
  ],
  pages: [
    { page: 1, title: 'Application Type' },
    { page: 2, title: 'Personal Information', conditional: 'applicationType is individual' },
    { page: 3, title: 'Business Information', conditional: 'applicationType is business' },
    { page: 4, title: 'Premium Features' },
    { page: 5, title: 'Premium Options', conditional: 'needsPremium is true' },
    { page: 6, title: 'Contact Information' },
  ],
  optionsUsed: ['pages.conditional', 'fields.conditional', 'progress.showSteps', 'progress.showPercentage'],
  returnHelpersUsed: ['Form'],
  assertionsRequired: [
    'individual path visible pages are 1, 2, 4, and 6 when needsPremium is false',
    'business path visible pages are 1, 3, 4, and 6 when needsPremium is false',
    'premium page 5 is inserted for both paths when needsPremium is true',
  ],
} satisfies CompatibilityExample;

export const persistenceCompatibilityExample = {
  id: 'persistence-form',
  group: 'behavior',
  sourceFile: persistenceSource,
  publicBehavior: [
    'compatibility examples preserve a three-page project inquiry form with localStorage persistence.',
    'Persistence excludes agreeToTerms, debounces writes, and restores on mount.',
    'Sections group contact information, project requirements, and project details.',
  ],
  schemaFields: {
    name: ['string', 'required'],
    email: ['string', 'email', 'required'],
    phone: ['string', 'required'],
    company: ['string', 'required'],
    jobTitle: ['string', 'required'],
    projectType: ['array', 'required'],
    timeline: ['string', 'required'],
    budget: ['string', 'required'],
    description: ['string', 'required'],
    agreeToTerms: ['boolean', 'required'],
  },
  fields: [
    { name: 'name', type: 'text', page: 1, config: ['section:Contact Information'] },
    { name: 'email', type: 'email', page: 1 },
    { name: 'phone', type: 'phone', page: 1 },
    { name: 'company', type: 'text', page: 1 },
    { name: 'jobTitle', type: 'text', page: 1 },
    { name: 'projectType', type: 'multiSelect', page: 2, options: ['web-dev', 'mobile-app', 'ecommerce', 'api', 'consulting'], config: ['searchable', 'maxSelections:3'] },
    { name: 'timeline', type: 'select', page: 2, options: ['ASAP', '1-3 months', '3-6 months', '6+ months', 'Flexible'] },
    { name: 'budget', type: 'radio', page: 2, options: ['<25k', '25k-75k', '75k-150k', '150k+'] },
    { name: 'description', type: 'textarea', page: 3, config: ['rows:6', 'showWordCount', 'maxLength:1000'] },
    { name: 'agreeToTerms', type: 'checkbox', page: 3 },
  ],
  pages: [
    { page: 1, title: 'Contact Information' },
    { page: 2, title: 'Project Requirements' },
    { page: 3, title: 'Final Details' },
  ],
  optionsUsed: ['persistence.key', 'persistence.storage', 'persistence.debounceMs', 'persistence.exclude', 'persistence.restoreOnMount'],
  returnHelpersUsed: ['Form'],
  assertionsRequired: [
    'persistence key is demo-project-inquiry-form',
    'storage mode is localStorage with debounceMs 1500',
    'agreeToTerms is excluded from persisted payloads',
  ],
} satisfies CompatibilityExample;

export const tabbedCompatibilityExample = {
  id: 'tabbed-form',
  group: 'behavior',
  sourceFile: tabbedSource,
  publicBehavior: [
    'compatibility examples preserve tab grouping across personal, preferences, and settings tabs.',
    'Fields are associated by tab id, not page number.',
    'Default settings initialize theme to auto, language to en, privacy to private, and analytics to true.',
  ],
  schemaFields: {
    firstName: ['string', 'required'],
    lastName: ['string', 'required'],
    email: ['string', 'email', 'required'],
    phone: ['string', 'required'],
    theme: ['enum', 'required'],
    language: ['enum', 'required'],
    notifications: ['boolean'],
    newsletter: ['boolean'],
    privacy: ['enum', 'required'],
    marketing: ['boolean'],
    analytics: ['boolean'],
    location: ['string', 'optional'],
  },
  fields: [
    { name: 'firstName', type: 'text', tab: 'personal' },
    { name: 'lastName', type: 'text', tab: 'personal' },
    { name: 'email', type: 'email', tab: 'personal' },
    { name: 'phone', type: 'phone', tab: 'personal' },
    { name: 'theme', type: 'select', tab: 'preferences', options: ['light', 'dark', 'auto'] },
    { name: 'language', type: 'select', tab: 'preferences', options: ['en', 'es', 'fr', 'de'] },
    { name: 'notifications', type: 'switch', tab: 'preferences' },
    { name: 'newsletter', type: 'switch', tab: 'preferences' },
    { name: 'privacy', type: 'radio', tab: 'settings', options: ['public', 'private', 'friends'] },
    { name: 'marketing', type: 'checkbox', tab: 'settings' },
    { name: 'analytics', type: 'checkbox', tab: 'settings' },
    { name: 'location', type: 'text', tab: 'settings' },
  ],
  tabs: ['personal', 'preferences', 'settings'],
  optionsUsed: ['tabs', 'field.tab', 'formOptions.defaultValues'],
  returnHelpersUsed: ['Form'],
  assertionsRequired: [
    'personal tab contains firstName, lastName, email, and phone',
    'preferences tab contains theme, language, notifications, and newsletter',
    'settings tab contains privacy, marketing, analytics, and location',
  ],
} satisfies CompatibilityExample;

export const rentalCarFlowCompatibilityExample = {
  id: 'rental-car-flow-form',
  group: 'behavior',
  sourceFile: rentalCarFlowSource,
  publicBehavior: [
    'compatibility examples preserve a nineteen-page one-field-per-page rental car flow.',
    'Dynamic text interpolates firstName and destination throughout labels, descriptions, placeholders, and page copy.',
    'Special requirements, insurance type, and child seat count pages are conditionally navigable.',
  ],
  schemaFields: {
    firstName: ['string', 'required'],
    destination: ['string', 'required'],
    tripPurpose: ['enum', 'required'],
    pickupDate: ['string', 'required'],
    returnDate: ['string', 'required'],
    passengerCount: ['number', 'required'],
    luggageAmount: ['enum', 'required'],
    carCategory: ['enum', 'required'],
    fuelPreference: ['enum', 'required'],
    hasSpecialNeeds: ['boolean'],
    specialRequirements: ['string', 'optional'],
    budgetRange: ['enum', 'required'],
    needsInsurance: ['boolean'],
    insuranceType: ['enum', 'optional'],
    wantsGPS: ['boolean'],
    wantsChildSeat: ['boolean'],
    childSeatCount: ['number', 'optional'],
    phone: ['string', 'required'],
    email: ['string', 'email', 'required'],
  },
  fields: [
    { name: 'firstName', type: 'text', page: 1, config: ['help.tooltip'] },
    { name: 'destination', type: 'text', page: 2, config: ['dynamicText:firstName'] },
    { name: 'tripPurpose', type: 'radio', page: 3, options: ['business', 'vacation', 'weekend_getaway', 'family_visit', 'other'], config: ['dynamicText:firstName,destination'] },
    { name: 'pickupDate', type: 'date', page: 4, config: ['disablePastDates', 'dynamicText'] },
    { name: 'returnDate', type: 'date', page: 5, config: ['disableDate:afterPickupDate', 'dynamicText'] },
    { name: 'passengerCount', type: 'slider', page: 6, config: ['min:1', 'max:8', 'valueMapping'] },
    { name: 'luggageAmount', type: 'radio', page: 7, options: ['minimal', 'moderate', 'heavy'] },
    { name: 'carCategory', type: 'select', page: 8, options: ['economy', 'compact', 'midsize', 'full_size', 'luxury', 'suv', 'convertible'] },
    { name: 'fuelPreference', type: 'radio', page: 9, options: ['gas', 'hybrid', 'electric'] },
    { name: 'hasSpecialNeeds', type: 'switch', page: 10 },
    { name: 'specialRequirements', type: 'textarea', page: 11, conditional: 'hasSpecialNeeds is true', config: ['rows:4', 'maxLength:500'] },
    { name: 'budgetRange', type: 'radio', page: 12, options: ['under_50', '50_100', '100_150', '150_plus'] },
    { name: 'needsInsurance', type: 'switch', page: 13 },
    { name: 'insuranceType', type: 'radio', page: 14, conditional: 'needsInsurance is true', options: ['basic', 'premium', 'comprehensive'] },
    { name: 'wantsGPS', type: 'switch', page: 15 },
    { name: 'wantsChildSeat', type: 'switch', page: 16 },
    { name: 'childSeatCount', type: 'slider', page: 17, conditional: 'wantsChildSeat is true', config: ['min:1', 'max:4'] },
    { name: 'phone', type: 'phone', page: 18, config: ['format:national', 'defaultCountry:US'] },
    { name: 'email', type: 'email', page: 19, config: ['dynamicPlaceholder', 'help.tooltip'] },
  ],
  pages: [
    { page: 1, title: 'Welcome to Your Perfect Rental Experience!' },
    { page: 2, title: 'Hello {{firstName}}!' },
    { page: 3, title: '{{destination}} Sounds Amazing!' },
    { page: 4, title: 'Trip Planning' },
    { page: 5, title: 'Perfect Timing!' },
    { page: 6, title: 'Travel Companions' },
    { page: 7, title: 'Packing Plans' },
    { page: 8, title: 'Choose Your Ride' },
    { page: 9, title: 'Fuel Your Adventure' },
    { page: 10, title: 'Accessibility & Comfort' },
    { page: 11, title: 'Special Accommodations' },
    { page: 12, title: 'Budget Considerations' },
    { page: 13, title: 'Protection & Peace of Mind' },
    { page: 14, title: 'Coverage Level' },
    { page: 15, title: 'Navigation & Convenience' },
    { page: 16, title: 'Family Safety' },
    { page: 17, title: 'Child Seat Setup' },
    { page: 18, title: 'Stay Connected' },
    { page: 19, title: 'Almost Done!' },
  ],
  optionsUsed: ['pages', 'dynamic text tokens', 'field.conditional', 'dateConfig', 'sliderConfig', 'phoneConfig', 'nextLabel', 'previousLabel', 'submitLabel', 'formClassName'],
  returnHelpersUsed: ['Form'],
  assertionsRequired: [
    'navigation skips page 11 unless hasSpecialNeeds is true',
    'navigation skips page 14 unless needsInsurance is true',
    'navigation skips page 17 unless wantsChildSeat is true',
    'firstName and destination tokens render in later labels and page copy',
  ],
} satisfies CompatibilityExample;

export const analyticsTrackingCompatibilityExample = {
  id: 'analytics-tracking-form',
  group: 'behavior',
  sourceFile: analyticsTrackingSource,
  publicBehavior: [
    'compatibility examples preserve analytics callback wiring for form start, field focus, field blur, page change, completion, and abandonment.',
    'The example remains a three-page lead form with company info, project details, and timeline details.',
    'Completion callback receives elapsed time and submitted form data.',
  ],
  schemaFields: {
    email: ['string', 'email', 'required'],
    companySize: ['enum', 'required'],
    interests: ['array', 'required'],
    budget: ['enum', 'required'],
    timeline: ['string', 'required'],
    description: ['string', 'required'],
  },
  fields: [
    { name: 'email', type: 'email', page: 1 },
    { name: 'companySize', type: 'select', page: 1, options: ['1-10', '11-50', '51-200', '200+'] },
    { name: 'interests', type: 'multiSelect', page: 2, options: ['web-dev', 'mobile', 'ecommerce', 'analytics', 'automation'] },
    { name: 'budget', type: 'radio', page: 2, options: ['<10k', '10k-50k', '50k-100k', '100k+'] },
    { name: 'timeline', type: 'select', page: 3, options: ['ASAP', '1-3 months', '3-6 months', '6+ months'] },
    { name: 'description', type: 'textarea', page: 3, config: ['rows:4', 'showWordCount', 'maxLength:500'] },
  ],
  pages: [
    { page: 1, title: 'Company Info' },
    { page: 2, title: 'Project Details' },
    { page: 3, title: 'Timeline & Details' },
  ],
  optionsUsed: ['analytics.onFormStart', 'analytics.onFieldFocus', 'analytics.onFieldBlur', 'analytics.onPageChange', 'analytics.onFormComplete', 'analytics.onFormAbandon'],
  returnHelpersUsed: ['Form'],
  assertionsRequired: [
    'analytics configuration accepts all six callback hooks',
    'onPageChange receives fromPage, toPage, and timeSpent',
    'onFormComplete receives timeSpent and formData',
  ],
} satisfies CompatibilityExample;
