import { describe, it } from 'node:test';

import { assertHasViolations, assertNoViolations, collectRepositoryTextFiles, isFileWritingScript, type RepositoryFile } from './utils.js';

// The contract targets scripts that write Formedible source files. Scripts that
// only write deploy metadata (empty marker files, CNAME), JSON manifests, or
// copy built dist output are not assembling Formedible source, so the
// writeFile-content checks below flag only content that looks like generated
// module source (comment headers or export/import statements), per
// FROM-SCRATCH-2.md "Sync Model" (no headers, no rewritten source, no
// replacement entry files). The `.js`-suffix import smells are scoped to
// Formedible-referencing specifiers: sibling-script imports such as
// './create-release-assets.js' are normal Node ESM, not ESM-rewritten source.
const forbiddenSyncPatterns = [
  /generated by formedible/i,
  /do not edit/i,
  /\.replace(?:All)?\s*\([^)]*formedible[^)]*\.m?js/i,
  /from\s+['"][^'"]*formedible[^'"]*\.m?js['"]/i,
  /ensure(?:Package|Root|Index|Entry)/,
  /replacement\s+entry/i,
  /@formedible\/ui\/lib\/formedible\//,
];

const variableAssignmentStartPattern = /\b(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*/g;
const writeFileCallPattern = /\bwriteFile(?:Sync)?\s*\(/g;
// String-literal prefixes that mark content as generated module source: an
// injected comment header or an export/import statement.
const generatedSourcePrefixPattern = /^\s*(?:\/\/|\/\*|export\b|import\b)/;
const templateInterpolationPattern = /\$\{[\s\S]*?\}/g;

interface CodeScanState {
  readonly openers: string[];
  readonly quotes: string[];
  comment: 'line' | 'block' | null;
  escaped: boolean;
}

function createCodeScanState(): CodeScanState {
  return { openers: [], quotes: [], comment: null, escaped: false };
}

// Runs `visitTopLevelCharacter` for every character of `text` that sits at the
// top level of a code expression: not inside a string or template literal
// (including `${...}` interpolations), not inside a comment, and not inside a
// nested (), [], or {} grouping. Returning true from the visitor stops the
// scan. This is what makes argument extraction string-literal aware, so a comma
// inside quotes or inside join(root, name) can no longer hide or split the real
// arguments of a writeFile call.
function scanTopLevelCharacters(text: string, startIndex: number, visitTopLevelCharacter: (character: string, index: number) => boolean): void {
  const state = createCodeScanState();

  for (let index = startIndex; index < text.length; index += 1) {
    const character = text[index];
    const next = index + 1 < text.length ? text[index + 1] : undefined;

    if (character === undefined) {
      return;
    }

    if (state.comment === 'line') {
      if (character === '\n') {
        state.comment = null;
      }

      continue;
    }

    if (state.comment === 'block') {
      if (character === '*' && next === '/') {
        state.comment = null;
        index += 1;
      }

      continue;
    }

    const activeQuote = state.quotes.at(-1);

    if (activeQuote !== undefined) {
      if (state.escaped) {
        state.escaped = false;
        continue;
      }

      if (character === '\\') {
        state.escaped = true;
        continue;
      }

      if (activeQuote === '`' && character === '$' && next === '{') {
        state.openers.push('${');
        state.quotes.pop();
        index += 1;
        continue;
      }

      if (character === activeQuote) {
        state.quotes.pop();
      }

      continue;
    }

    if (character === '/' && next === '/') {
      state.comment = 'line';
      index += 1;
      continue;
    }

    if (character === '/' && next === '*') {
      state.comment = 'block';
      index += 1;
      continue;
    }

    if (character === "'" || character === '"' || character === '`') {
      state.quotes.push(character);
      continue;
    }

    if (character === '(' || character === '[' || character === '{') {
      state.openers.push(character);
      continue;
    }

    if (character === ')' || character === ']' || character === '}') {
      const opener = state.openers.pop();

      if (character === '}' && opener === '${') {
        state.quotes.push('`');
        continue;
      }

      if (opener === undefined && visitTopLevelCharacter(character, index)) {
        return;
      }

      continue;
    }

    if (state.openers.length === 0 && visitTopLevelCharacter(character, index)) {
      return;
    }
  }
}

function findTopLevelSeparatorIndices(text: string, separator: string): number[] {
  const indices: number[] = [];

  scanTopLevelCharacters(text, 0, (character, index) => {
    if (character === separator) {
      indices.push(index);
    }

    return false;
  });

  return indices;
}

function splitAtIndices(text: string, indices: readonly number[]): string[] {
  const parts: string[] = [];
  let start = 0;

  for (const index of indices) {
    parts.push(text.slice(start, index));
    start = index + 1;
  }

  parts.push(text.slice(start));

  return parts.map((part) => part.trim()).filter((part) => part.length > 0);
}

// Returns the index of the `)` that closes the call whose argument list starts
// at `startIndex` (the character right after the opening parenthesis).
function findCallCloseIndex(content: string, startIndex: number): number {
  let closeIndex = -1;

  scanTopLevelCharacters(content, startIndex, (character, index) => {
    if (character === ')') {
      closeIndex = index;
      return true;
    }

    return false;
  });

  return closeIndex;
}

function extractWriteFileContentArguments(content: string): string[] {
  const args: string[] = [];

  for (const match of content.matchAll(writeFileCallPattern)) {
    const startIndex = (match.index ?? 0) + match[0].length;
    const closeIndex = findCallCloseIndex(content, startIndex);

    if (closeIndex === -1) {
      continue;
    }

    const argumentList = content.slice(startIndex, closeIndex);
    const separators = findTopLevelSeparatorIndices(argumentList, ',');

    for (const argument of splitAtIndices(argumentList, separators)) {
      args.push(argument);
    }
  }

  return args;
}

function readStringLiteralRawText(operand: string): string | undefined {
  const trimmed = operand.trim();
  const quote = trimmed[0];

  if ((quote !== "'" && quote !== '"' && quote !== '`') || trimmed.length < 2 || trimmed.at(-1) !== quote) {
    return undefined;
  }

  return trimmed.slice(1, -1);
}

function isGeneratedSourceLiteral(operand: string): boolean {
  const rawText = readStringLiteralRawText(operand);

  if (rawText === undefined) {
    return false;
  }

  return generatedSourcePrefixPattern.test(rawText.replace(templateInterpolationPattern, ''));
}

function operandAssemblesGeneratedSource(operand: string, trackedVariables: ReadonlySet<string>): boolean {
  if (trackedVariables.has(operand) || isGeneratedSourceLiteral(operand)) {
    return true;
  }

  const rawText = readStringLiteralRawText(operand);

  if (rawText === undefined) {
    return false;
  }

  // Template interpolations are content too: `${'// header'}` or `${banner}`
  // must not smuggle generated source past the static-text check.
  return [...rawText.matchAll(/\$\{([^}]*)\}/g)].some((match) => {
    const interpolation = match[1];

    return interpolation !== undefined && assemblesGeneratedSource(interpolation, trackedVariables);
  });
}

// An expression assembles generated source when any operand of its top-level
// concatenation chain is a source-like literal, a template interpolation that
// assembles source, or an already-tracked variable (tracked variables on
// either side of the `+` are caught by the same rule).
function assemblesGeneratedSource(expression: string, trackedVariables: ReadonlySet<string>): boolean {
  return splitAtIndices(expression, findTopLevelSeparatorIndices(expression, '+')).some((operand) =>
    operandAssemblesGeneratedSource(operand, trackedVariables),
  );
}

function collectGeneratedContentVariables(content: string): Set<string> {
  const variables = new Set<string>();

  for (const match of content.matchAll(variableAssignmentStartPattern)) {
    const variableName = match[1];
    const startIndex = (match.index ?? 0) + match[0].length;
    const terminator = findTopLevelSeparatorIndices(content.slice(startIndex), ';')[0];
    const expression = terminator === undefined ? content.slice(startIndex) : content.slice(startIndex, startIndex + terminator);

    if (variableName !== undefined && assemblesGeneratedSource(expression, variables)) {
      variables.add(variableName);
    }
  }

  return variables;
}

function findWriteFileMutationViolations(file: RepositoryFile): string[] {
  const generatedVariables = collectGeneratedContentVariables(file.content);

  return extractWriteFileContentArguments(file.content)
    .filter((argument) => assemblesGeneratedSource(argument, generatedVariables))
    .map((argument) => `sync contract violation in ${file.relativePath}: writeFile content assembles generated source: ${argument}`);
}

export function findCopyOnlySyncContractViolations(files: readonly RepositoryFile[]): string[] {
  return files
    .filter(isFileWritingScript)
    .flatMap((file) =>
      forbiddenSyncPatterns
        .filter((pattern) => pattern.test(file.content))
        .map((pattern) => `sync contract violation in ${file.relativePath}: ${pattern.source}`)
        .concat(findWriteFileMutationViolations(file)),
    );
}

describe('quick sync contract', () => {
  it('rejects sample sync that writes assembled generated content', () => {
    assertHasViolations(
      findCopyOnlySyncContractViolations([
        {
          relativePath: 'scripts/quick-sync.ts',
          content: "await writeFile(target, '// generated by Formedible\\n' + source);",
        },
      ]),
    );
  });

  it('rejects sample sync that writes generated content behind a parenthesized first argument', () => {
    assertHasViolations(
      findCopyOnlySyncContractViolations([
        {
          relativePath: 'scripts/quick-sync.ts',
          content: "await writeFile(join(root, 'formedible.ts'), 'export const generated = true;');",
        },
      ]),
    );
  });

  it('rejects sample sync that hides a header behind a comma inside a string literal', () => {
    assertHasViolations(
      findCopyOnlySyncContractViolations([
        {
          relativePath: 'scripts/quick-sync.ts',
          content: "await writeFile(target, 'x, ' + '// generated by Formedible\\n' + source);",
        },
      ]),
    );
  });

  it('rejects sample sync that assembles generated content through variables on either side of concatenation', () => {
    assertHasViolations(
      findCopyOnlySyncContractViolations([
        {
          relativePath: 'scripts/quick-sync.ts',
          content: "const header = `// generated by Formedible`;\nconst output = source + header;\nawait writeFile(target, output);",
        },
      ]),
    );
  });

  it('rejects sample sync that chains tracked variables through multiple assignments', () => {
    assertHasViolations(
      findCopyOnlySyncContractViolations([
        {
          relativePath: 'scripts/quick-sync.ts',
          content: "const banner = '// do not edit';\nconst body = banner;\nconst output = body + source;\nawait writeFile(target, output);",
        },
      ]),
    );
  });

  it('rejects sample sync that writes generated content through a template interpolation', () => {
    assertHasViolations(
      findCopyOnlySyncContractViolations([
        {
          relativePath: 'scripts/quick-sync.ts',
          content: "const banner = '// generated by Formedible';\nawait writeFile(target, `${banner}\\n` + source);",
        },
      ]),
    );
  });

  it('rejects sample sync that writes a template literal starting with an export statement', () => {
    assertHasViolations(
      findCopyOnlySyncContractViolations([
        {
          relativePath: 'scripts/quick-sync.ts',
          content: 'const output = `export const generated = true;`;\nawait writeFile(target, output);',
        },
      ]),
    );
  });

  it('allows sample sync that rewrites registry aliases before writing', () => {
    assertNoViolations(
      findCopyOnlySyncContractViolations([
        {
          relativePath: 'scripts/quick-sync.ts',
          content: 'const output = rewriteModuleSpecifiers(source, aliases);\nawait writeFile(target, output);',
        },
      ]),
    );
  });

  it('allows sample sync that passes copied content through an alias rewrite function', () => {
    assertNoViolations(
      findCopyOnlySyncContractViolations([
        {
          relativePath: 'scripts/quick-sync.ts',
          content: 'await writeFile(target, rewriteModuleSpecifiers(source, aliases));',
        },
      ]),
    );
  });

  it('allows sample sync that writes the same bytes it read', () => {
    assertNoViolations(
      findCopyOnlySyncContractViolations([
        {
          relativePath: 'scripts/quick-sync.ts',
          content: 'const source = await readFile(sourcePath);\nawait writeFile(target, source);',
        },
      ]),
    );
  });

  it('allows sample deploy script that writes marker and manifest files without generated source', () => {
    assertNoViolations(
      findCopyOnlySyncContractViolations([
        {
          relativePath: 'scripts/prepare-web-deploy.js',
          content: "const customDomain = 'formedible.dev';\nawait writeFile(resolve(outputDirectory, '.nojekyll'), '', 'utf8');\nawait writeFile(resolve(outputDirectory, 'CNAME'), customDomain, 'utf8');\nawait copyFile(registrySource, registryDestination);",
        },
      ]),
    );
  });

  it('allows sample release script that writes a JSON manifest with an interpolated template', () => {
    assertNoViolations(
      findCopyOnlySyncContractViolations([
        {
          relativePath: 'scripts/build-release.js',
          content: "import { createReleaseAssets } from './create-release-assets.js';\nawait writeFile(packageJsonPath, `${JSON.stringify(packageJson, null, 2)}\\n`, 'utf8');",
        },
      ]),
    );
  });

  it('ignores sample documentation that is not a writer script', () => {
    assertNoViolations(
      findCopyOnlySyncContractViolations([
        {
          relativePath: 'scripts/README.md',
          content: "await writeFile(target, '// generated by Formedible\\n' + source);",
        },
      ]),
    );
  });

  it('ignores sample script that never writes files', () => {
    assertNoViolations(
      findCopyOnlySyncContractViolations([
        {
          relativePath: 'scripts/validate-example.js',
          content: "const output = '// generated by Formedible';\nconsole.info(output);",
        },
      ]),
    );
  });

  it('rejects invalid sync content generation in the repository', async () => {
    assertNoViolations(findCopyOnlySyncContractViolations(await collectRepositoryTextFiles()));
  });
});
