import { describe, it } from 'node:test';
import { assertHasViolations, assertNoViolations, collectRepositoryTextFiles } from './utils.js';
const syncPathPattern = /^scripts\/.*sync.*\.(?:cjs|js|mjs|ts)$/;
const forbiddenSyncPatterns = [
    /writeFile\s*\([^,]+,\s*[`'"]\/\//,
    /generated by formedible/i,
    /do not edit/i,
    /\.replace(?:All)?\s*\([^)]*\.m?js/,
    /from\s+['"][^'"]+\.m?js['"]/,
    /writeFile\s*\([^,]+,\s*(?:`|['"])(?:export|import)\b/,
    /ensure(?:Package|Root|Index|Entry)/,
    /replacement\s+entry/i,
];
const variableAssignmentPattern = /\b(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*([^;]+)/g;
function extractWriteFileContentArguments(content) {
    const args = [];
    const writeFilePattern = /\bwriteFile(?:Sync)?\s*\(/g;
    for (const match of content.matchAll(writeFilePattern)) {
        let depth = 1;
        let commaIndex = -1;
        const startIndex = match.index + match[0].length;
        for (let index = startIndex; index < content.length; index += 1) {
            const character = content[index];
            if (character === '(') {
                depth += 1;
            }
            if (character === ')') {
                depth -= 1;
            }
            if (character === ',' && depth === 1 && commaIndex === -1) {
                commaIndex = index;
            }
            if (depth === 0) {
                if (commaIndex !== -1) {
                    args.push(content.slice(commaIndex + 1, index).trim());
                }
                break;
            }
        }
    }
    return args;
}
function isTransformedContentExpression(expression) {
    const trimmedExpression = expression.trim();
    return (trimmedExpression.startsWith('`') ||
        trimmedExpression.startsWith("'") ||
        trimmedExpression.startsWith('"') ||
        trimmedExpression.includes('+') ||
        /\$\{[^}]+\}/.test(trimmedExpression) ||
        /\.[A-Za-z_$][\w$]*\s*\(/.test(trimmedExpression) ||
        /^[A-Za-z_$][\w$]*\s*\(/.test(trimmedExpression));
}
function collectTransformedContentVariables(content) {
    const variables = new Set();
    for (const match of content.matchAll(variableAssignmentPattern)) {
        const variableName = match[1];
        const expression = match[2];
        if (variableName !== undefined && expression !== undefined && isTransformedContentExpression(expression)) {
            variables.add(variableName);
        }
    }
    return variables;
}
function findWriteFileMutationViolations(file) {
    const transformedVariables = collectTransformedContentVariables(file.content);
    return extractWriteFileContentArguments(file.content)
        .filter((argument) => isTransformedContentExpression(argument) || transformedVariables.has(argument))
        .map((argument) => `copy-only sync contract violation in ${file.relativePath}: writeFile content mutates source: ${argument}`);
}
export function findCopyOnlySyncContractViolations(files) {
    return files
        .filter((file) => syncPathPattern.test(file.relativePath))
        .flatMap((file) => forbiddenSyncPatterns
        .filter((pattern) => pattern.test(file.content))
        .map((pattern) => `copy-only sync contract violation in ${file.relativePath}: ${pattern.source}`)
        .concat(findWriteFileMutationViolations(file)));
}
describe('copy-only sync contract', () => {
    it('rejects sample sync that writes transformed or assembled content instead of copying files', () => {
        assertHasViolations(findCopyOnlySyncContractViolations([
            {
                relativePath: 'scripts/quick-sync.ts',
                content: "await writeFile(target, '// generated by Formedible\\n' + source.replace(/from '(.+)'/g, \"from '$1.js'\"));",
            },
        ]));
    });
    it('rejects sample sync that mutates content through variables before writing', () => {
        assertHasViolations(findCopyOnlySyncContractViolations([
            {
                relativePath: 'scripts/quick-sync.ts',
                content: "const output = source.trim();\nawait writeFile(target, output);",
            },
        ]));
    });
    it('rejects sample sync that passes copied content through a transform function', () => {
        assertHasViolations(findCopyOnlySyncContractViolations([
            {
                relativePath: 'scripts/quick-sync.ts',
                content: 'await writeFile(target, transform(source));',
            },
        ]));
    });
    it('allows sample sync that writes the same bytes it read', () => {
        assertNoViolations(findCopyOnlySyncContractViolations([
            {
                relativePath: 'scripts/quick-sync.ts',
                content: 'const source = await readFile(sourcePath);\nawait writeFile(target, source);',
            },
        ]));
    });
    it('rejects sync content mutation in the repository', async () => {
        assertNoViolations(findCopyOnlySyncContractViolations(await collectRepositoryTextFiles()));
    });
});
