import { describe, it } from 'node:test';
import { assertHasViolations, assertNoViolations, collectRepositoryTextFiles } from './utils.js';
const syncPathPattern = /^scripts\/.*sync.*\.(?:cjs|js|mjs|ts)$/;
const forbiddenSyncPatterns = [
    /writeFile\s*\([^,]+,\s*[`'"]\/\//,
    /generated by formedible/i,
    /do not edit/i,
    /\.replace(?:All)?\s*\([^)]*\.m?js/,
    /from\s+['"][^'"]+\.m?js['"]/,
    /writeFile\s*\([^,]+,\s*(?:`|['"])(?:export|import)\b/,
    /ensure(?:Package|Root|Index|Entry)/,
    /replacement\s+entry/i,
    /@formedible\/ui\/lib\/formedible\//,
];
const variableAssignmentPattern = /\b(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*([^;]+)/g;
function extractWriteFileContentArguments(content) {
    const args = [];
    const writeFilePattern = /\bwriteFile(?:Sync)?\s*\(/g;
    for (const match of content.matchAll(writeFilePattern)) {
        let depth = 1;
        let commaIndex = -1;
        const startIndex = match.index + match[0].length;
        for (let index = startIndex; index < content.length; index += 1) {
            const character = content[index];
            if (character === '(') {
                depth += 1;
            }
            if (character === ')') {
                depth -= 1;
            }
            if (character === ',' && depth === 1 && commaIndex === -1) {
                commaIndex = index;
            }
            if (depth === 0) {
                if (commaIndex !== -1) {
                    args.push(content.slice(commaIndex + 1, index).trim());
                }
                break;
            }
        }
    }
    return args;
}
function isGeneratedContentExpression(expression) {
    const trimmedExpression = expression.trim();
    return trimmedExpression.startsWith('`') || trimmedExpression.startsWith("'") || trimmedExpression.startsWith('"') || /\$\{[^}]+\}/.test(trimmedExpression);
}
function collectGeneratedContentVariables(content) {
    const variables = new Set();
    for (const match of content.matchAll(variableAssignmentPattern)) {
        const variableName = match[1];
        const expression = match[2];
        if (variableName !== undefined && expression !== undefined && isGeneratedContentExpression(expression)) {
            variables.add(variableName);
        }
    }
    return variables;
}
function findWriteFileMutationViolations(file) {
    const generatedVariables = collectGeneratedContentVariables(file.content);
    return extractWriteFileContentArguments(file.content)
        .filter((argument) => isGeneratedContentExpression(argument) || generatedVariables.has(argument))
        .map((argument) => `sync contract violation in ${file.relativePath}: writeFile content assembles generated source: ${argument}`);
}
export function findCopyOnlySyncContractViolations(files) {
    return files
        .filter((file) => syncPathPattern.test(file.relativePath))
        .flatMap((file) => forbiddenSyncPatterns
        .filter((pattern) => pattern.test(file.content))
        .map((pattern) => `sync contract violation in ${file.relativePath}: ${pattern.source}`)
        .concat(findWriteFileMutationViolations(file)));
}
describe('quick sync contract', () => {
    it('rejects sample sync that writes assembled generated content', () => {
        assertHasViolations(findCopyOnlySyncContractViolations([
            {
                relativePath: 'scripts/quick-sync.ts',
                content: "await writeFile(target, '// generated by Formedible\\n' + source);",
            },
        ]));
    });
    it('allows sample sync that rewrites registry aliases before writing', () => {
        assertNoViolations(findCopyOnlySyncContractViolations([
            {
                relativePath: 'scripts/quick-sync.ts',
                content: 'const output = rewriteModuleSpecifiers(source, aliases);\nawait writeFile(target, output);',
            },
        ]));
    });
    it('rejects sample sync that assembles generated content through variables before writing', () => {
        assertHasViolations(findCopyOnlySyncContractViolations([
            {
                relativePath: 'scripts/quick-sync.ts',
                content: 'const output = `export const generated = true;`;\nawait writeFile(target, output);',
            },
        ]));
    });
    it('allows sample sync that passes copied content through an alias rewrite function', () => {
        assertNoViolations(findCopyOnlySyncContractViolations([
            {
                relativePath: 'scripts/quick-sync.ts',
                content: 'await writeFile(target, rewriteModuleSpecifiers(source, aliases));',
            },
        ]));
    });
    it('allows sample sync that writes the same bytes it read', () => {
        assertNoViolations(findCopyOnlySyncContractViolations([
            {
                relativePath: 'scripts/quick-sync.ts',
                content: 'const source = await readFile(sourcePath);\nawait writeFile(target, source);',
            },
        ]));
    });
    it('rejects invalid sync content generation in the repository', async () => {
        assertNoViolations(findCopyOnlySyncContractViolations(await collectRepositoryTextFiles()));
    });
});
