/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrototypeRouteImport } from './routes/prototype'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as AiBuilderRouteImport } from './routes/ai-builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrototypeIndexRouteImport } from './routes/prototype.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as PrototypeMiseEnPlaceRouteImport } from './routes/prototype.mise-en-place'
import { Route as PrototypeLeCellierRouteImport } from './routes/prototype.le-cellier'
import { Route as PrototypeLaTableRouteImport } from './routes/prototype.la-table'
import { Route as PrototypeLaCarteRouteImport } from './routes/prototype.la-carte'
import { Route as DocsValidationRouteImport } from './routes/docs.validation'
import { Route as DocsPersistenceRouteImport } from './routes/docs.persistence'
import { Route as DocsParserRouteImport } from './routes/docs.parser'
import { Route as DocsGettingStartedRouteImport } from './routes/docs.getting-started'
import { Route as DocsFieldsRouteImport } from './routes/docs.fields'
import { Route as DocsExamplesRouteImport } from './routes/docs.examples'
import { Route as DocsDynamicTextRouteImport } from './routes/docs.dynamic-text'
import { Route as DocsBuilderRouteImport } from './routes/docs.builder'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as DocsAnalyticsRouteImport } from './routes/docs.analytics'
import { Route as DocsAiBuilderRouteImport } from './routes/docs.ai-builder'
import { Route as DocsAdvancedFeaturesRouteImport } from './routes/docs.advanced-features'

const PrototypeRoute = PrototypeRouteImport.update({
  id: '/prototype',
  path: '/prototype',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBuilderRoute = AiBuilderRouteImport.update({
  id: '/ai-builder',
  path: '/ai-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeIndexRoute = PrototypeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrototypeRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const PrototypeMiseEnPlaceRoute = PrototypeMiseEnPlaceRouteImport.update({
  id: '/mise-en-place',
  path: '/mise-en-place',
  getParentRoute: () => PrototypeRoute,
} as any)
const PrototypeLeCellierRoute = PrototypeLeCellierRouteImport.update({
  id: '/le-cellier',
  path: '/le-cellier',
  getParentRoute: () => PrototypeRoute,
} as any)
const PrototypeLaTableRoute = PrototypeLaTableRouteImport.update({
  id: '/la-table',
  path: '/la-table',
  getParentRoute: () => PrototypeRoute,
} as any)
const PrototypeLaCarteRoute = PrototypeLaCarteRouteImport.update({
  id: '/la-carte',
  path: '/la-carte',
  getParentRoute: () => PrototypeRoute,
} as any)
const DocsValidationRoute = DocsValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPersistenceRoute = DocsPersistenceRouteImport.update({
  id: '/persistence',
  path: '/persistence',
  getParentRoute: () => DocsRoute,
} as any)
const DocsParserRoute = DocsParserRouteImport.update({
  id: '/parser',
  path: '/parser',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFieldsRoute = DocsFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => DocsRoute,
} as any)
const DocsExamplesRoute = DocsExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDynamicTextRoute = DocsDynamicTextRouteImport.update({
  id: '/dynamic-text',
  path: '/dynamic-text',
  getParentRoute: () => DocsRoute,
} as any)
const DocsBuilderRoute = DocsBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAnalyticsRoute = DocsAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAiBuilderRoute = DocsAiBuilderRouteImport.update({
  id: '/ai-builder',
  path: '/ai-builder',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAdvancedFeaturesRoute = DocsAdvancedFeaturesRouteImport.update({
  id: '/advanced-features',
  path: '/advanced-features',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-builder': typeof AiBuilderRoute
  '/builder': typeof BuilderRoute
  '/docs': typeof DocsRouteWithChildren
  '/prototype': typeof PrototypeRouteWithChildren
  '/docs/advanced-features': typeof DocsAdvancedFeaturesRoute
  '/docs/ai-builder': typeof DocsAiBuilderRoute
  '/docs/analytics': typeof DocsAnalyticsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/builder': typeof DocsBuilderRoute
  '/docs/dynamic-text': typeof DocsDynamicTextRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/fields': typeof DocsFieldsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/parser': typeof DocsParserRoute
  '/docs/persistence': typeof DocsPersistenceRoute
  '/docs/validation': typeof DocsValidationRoute
  '/prototype/la-carte': typeof PrototypeLaCarteRoute
  '/prototype/la-table': typeof PrototypeLaTableRoute
  '/prototype/le-cellier': typeof PrototypeLeCellierRoute
  '/prototype/mise-en-place': typeof PrototypeMiseEnPlaceRoute
  '/docs/': typeof DocsIndexRoute
  '/prototype/': typeof PrototypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-builder': typeof AiBuilderRoute
  '/builder': typeof BuilderRoute
  '/docs/advanced-features': typeof DocsAdvancedFeaturesRoute
  '/docs/ai-builder': typeof DocsAiBuilderRoute
  '/docs/analytics': typeof DocsAnalyticsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/builder': typeof DocsBuilderRoute
  '/docs/dynamic-text': typeof DocsDynamicTextRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/fields': typeof DocsFieldsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/parser': typeof DocsParserRoute
  '/docs/persistence': typeof DocsPersistenceRoute
  '/docs/validation': typeof DocsValidationRoute
  '/prototype/la-carte': typeof PrototypeLaCarteRoute
  '/prototype/la-table': typeof PrototypeLaTableRoute
  '/prototype/le-cellier': typeof PrototypeLeCellierRoute
  '/prototype/mise-en-place': typeof PrototypeMiseEnPlaceRoute
  '/docs': typeof DocsIndexRoute
  '/prototype': typeof PrototypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-builder': typeof AiBuilderRoute
  '/builder': typeof BuilderRoute
  '/docs': typeof DocsRouteWithChildren
  '/prototype': typeof PrototypeRouteWithChildren
  '/docs/advanced-features': typeof DocsAdvancedFeaturesRoute
  '/docs/ai-builder': typeof DocsAiBuilderRoute
  '/docs/analytics': typeof DocsAnalyticsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/builder': typeof DocsBuilderRoute
  '/docs/dynamic-text': typeof DocsDynamicTextRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/fields': typeof DocsFieldsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/parser': typeof DocsParserRoute
  '/docs/persistence': typeof DocsPersistenceRoute
  '/docs/validation': typeof DocsValidationRoute
  '/prototype/la-carte': typeof PrototypeLaCarteRoute
  '/prototype/la-table': typeof PrototypeLaTableRoute
  '/prototype/le-cellier': typeof PrototypeLeCellierRoute
  '/prototype/mise-en-place': typeof PrototypeMiseEnPlaceRoute
  '/docs/': typeof DocsIndexRoute
  '/prototype/': typeof PrototypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-builder'
    | '/builder'
    | '/docs'
    | '/prototype'
    | '/docs/advanced-features'
    | '/docs/ai-builder'
    | '/docs/analytics'
    | '/docs/api'
    | '/docs/builder'
    | '/docs/dynamic-text'
    | '/docs/examples'
    | '/docs/fields'
    | '/docs/getting-started'
    | '/docs/parser'
    | '/docs/persistence'
    | '/docs/validation'
    | '/prototype/la-carte'
    | '/prototype/la-table'
    | '/prototype/le-cellier'
    | '/prototype/mise-en-place'
    | '/docs/'
    | '/prototype/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-builder'
    | '/builder'
    | '/docs/advanced-features'
    | '/docs/ai-builder'
    | '/docs/analytics'
    | '/docs/api'
    | '/docs/builder'
    | '/docs/dynamic-text'
    | '/docs/examples'
    | '/docs/fields'
    | '/docs/getting-started'
    | '/docs/parser'
    | '/docs/persistence'
    | '/docs/validation'
    | '/prototype/la-carte'
    | '/prototype/la-table'
    | '/prototype/le-cellier'
    | '/prototype/mise-en-place'
    | '/docs'
    | '/prototype'
  id:
    | '__root__'
    | '/'
    | '/ai-builder'
    | '/builder'
    | '/docs'
    | '/prototype'
    | '/docs/advanced-features'
    | '/docs/ai-builder'
    | '/docs/analytics'
    | '/docs/api'
    | '/docs/builder'
    | '/docs/dynamic-text'
    | '/docs/examples'
    | '/docs/fields'
    | '/docs/getting-started'
    | '/docs/parser'
    | '/docs/persistence'
    | '/docs/validation'
    | '/prototype/la-carte'
    | '/prototype/la-table'
    | '/prototype/le-cellier'
    | '/prototype/mise-en-place'
    | '/docs/'
    | '/prototype/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiBuilderRoute: typeof AiBuilderRoute
  BuilderRoute: typeof BuilderRoute
  DocsRoute: typeof DocsRouteWithChildren
  PrototypeRoute: typeof PrototypeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prototype': {
      id: '/prototype'
      path: '/prototype'
      fullPath: '/prototype'
      preLoaderRoute: typeof PrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-builder': {
      id: '/ai-builder'
      path: '/ai-builder'
      fullPath: '/ai-builder'
      preLoaderRoute: typeof AiBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/': {
      id: '/prototype/'
      path: '/'
      fullPath: '/prototype/'
      preLoaderRoute: typeof PrototypeIndexRouteImport
      parentRoute: typeof PrototypeRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/prototype/mise-en-place': {
      id: '/prototype/mise-en-place'
      path: '/mise-en-place'
      fullPath: '/prototype/mise-en-place'
      preLoaderRoute: typeof PrototypeMiseEnPlaceRouteImport
      parentRoute: typeof PrototypeRoute
    }
    '/prototype/le-cellier': {
      id: '/prototype/le-cellier'
      path: '/le-cellier'
      fullPath: '/prototype/le-cellier'
      preLoaderRoute: typeof PrototypeLeCellierRouteImport
      parentRoute: typeof PrototypeRoute
    }
    '/prototype/la-table': {
      id: '/prototype/la-table'
      path: '/la-table'
      fullPath: '/prototype/la-table'
      preLoaderRoute: typeof PrototypeLaTableRouteImport
      parentRoute: typeof PrototypeRoute
    }
    '/prototype/la-carte': {
      id: '/prototype/la-carte'
      path: '/la-carte'
      fullPath: '/prototype/la-carte'
      preLoaderRoute: typeof PrototypeLaCarteRouteImport
      parentRoute: typeof PrototypeRoute
    }
    '/docs/validation': {
      id: '/docs/validation'
      path: '/validation'
      fullPath: '/docs/validation'
      preLoaderRoute: typeof DocsValidationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/persistence': {
      id: '/docs/persistence'
      path: '/persistence'
      fullPath: '/docs/persistence'
      preLoaderRoute: typeof DocsPersistenceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/parser': {
      id: '/docs/parser'
      path: '/parser'
      fullPath: '/docs/parser'
      preLoaderRoute: typeof DocsParserRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/fields': {
      id: '/docs/fields'
      path: '/fields'
      fullPath: '/docs/fields'
      preLoaderRoute: typeof DocsFieldsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/examples': {
      id: '/docs/examples'
      path: '/examples'
      fullPath: '/docs/examples'
      preLoaderRoute: typeof DocsExamplesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/dynamic-text': {
      id: '/docs/dynamic-text'
      path: '/dynamic-text'
      fullPath: '/docs/dynamic-text'
      preLoaderRoute: typeof DocsDynamicTextRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/builder': {
      id: '/docs/builder'
      path: '/builder'
      fullPath: '/docs/builder'
      preLoaderRoute: typeof DocsBuilderRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/analytics': {
      id: '/docs/analytics'
      path: '/analytics'
      fullPath: '/docs/analytics'
      preLoaderRoute: typeof DocsAnalyticsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/ai-builder': {
      id: '/docs/ai-builder'
      path: '/ai-builder'
      fullPath: '/docs/ai-builder'
      preLoaderRoute: typeof DocsAiBuilderRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/advanced-features': {
      id: '/docs/advanced-features'
      path: '/advanced-features'
      fullPath: '/docs/advanced-features'
      preLoaderRoute: typeof DocsAdvancedFeaturesRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsAdvancedFeaturesRoute: typeof DocsAdvancedFeaturesRoute
  DocsAiBuilderRoute: typeof DocsAiBuilderRoute
  DocsAnalyticsRoute: typeof DocsAnalyticsRoute
  DocsApiRoute: typeof DocsApiRoute
  DocsBuilderRoute: typeof DocsBuilderRoute
  DocsDynamicTextRoute: typeof DocsDynamicTextRoute
  DocsExamplesRoute: typeof DocsExamplesRoute
  DocsFieldsRoute: typeof DocsFieldsRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsParserRoute: typeof DocsParserRoute
  DocsPersistenceRoute: typeof DocsPersistenceRoute
  DocsValidationRoute: typeof DocsValidationRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAdvancedFeaturesRoute: DocsAdvancedFeaturesRoute,
  DocsAiBuilderRoute: DocsAiBuilderRoute,
  DocsAnalyticsRoute: DocsAnalyticsRoute,
  DocsApiRoute: DocsApiRoute,
  DocsBuilderRoute: DocsBuilderRoute,
  DocsDynamicTextRoute: DocsDynamicTextRoute,
  DocsExamplesRoute: DocsExamplesRoute,
  DocsFieldsRoute: DocsFieldsRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsParserRoute: DocsParserRoute,
  DocsPersistenceRoute: DocsPersistenceRoute,
  DocsValidationRoute: DocsValidationRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface PrototypeRouteChildren {
  PrototypeLaCarteRoute: typeof PrototypeLaCarteRoute
  PrototypeLaTableRoute: typeof PrototypeLaTableRoute
  PrototypeLeCellierRoute: typeof PrototypeLeCellierRoute
  PrototypeMiseEnPlaceRoute: typeof PrototypeMiseEnPlaceRoute
  PrototypeIndexRoute: typeof PrototypeIndexRoute
}

const PrototypeRouteChildren: PrototypeRouteChildren = {
  PrototypeLaCarteRoute: PrototypeLaCarteRoute,
  PrototypeLaTableRoute: PrototypeLaTableRoute,
  PrototypeLeCellierRoute: PrototypeLeCellierRoute,
  PrototypeMiseEnPlaceRoute: PrototypeMiseEnPlaceRoute,
  PrototypeIndexRoute: PrototypeIndexRoute,
}

const PrototypeRouteWithChildren = PrototypeRoute._addFileChildren(
  PrototypeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiBuilderRoute: AiBuilderRoute,
  BuilderRoute: BuilderRoute,
  DocsRoute: DocsRouteWithChildren,
  PrototypeRoute: PrototypeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
